### PR TITLE
Adds necessary dependencies.

### PR DESCRIPTION
**Pull request by lambroisie**
I use a script to update my AddOns, but recently CurseForge has prevented it from working due to stringent Cloudflare settings. Would it be possible to add these libraries so I can clone from this repo instead? If not, would it be possible to update Bagnon more frequently on WoW Interface?

Here's the site in question:
https://www.wowinterface.com

### CODE REVIEW

**Comment by Jaliborc** [comment]
No, this doesnt match the actual addon, worse for us.

**Comment by lambroisie** [comment]
In what ways does it differ from the version on CurseForge? Can you be more specific please?

**Comment by Jaliborc** [comment]
1) Commits aren't working versions
2) No postprocessing
3) Bagnon is on the Addon root folder, not at Addons/Bagnon/Bagnon. Same applies to everything else.
4) Use curseforge

**Comment by Tuller** [comment]
Wowi has an api as well, so it should be not too terrible to post stuff there. Alternatively, You can add formal builds to GitHub tagged releases

**Pull request closed without merging**
